### PR TITLE
Issue 9 and 11  

### PR DESCRIPTION
**Pull request by anushka255**
Modified the hello template - `hello.jinja` to only use bash and created a working python version of it - `pyhello.jinja`.

### CODE REVIEW

**Comment by vineetbansal** [comment]
Thanks - I feel like we've been through this a few times now and should stick to this process - each separate issue you tackle should have its own branch (prefixed with your own initials), should originate from the branch that is your eventual merge target (`main` in this case), and should have it's own corresponding PR.

The specific reason I say this here is that you're handling issues 9, 11 and 12 here (despite what the title of this PR indicates), and while #9 is straightforward and can be merged, I have follow-ups about 11 and 12 which are independent and will likely proceed at different paces (and entail their own independent discussions).

**Review by vineetbansal — COMMENTED** [review]
Please open one PR per issue, from a descriptively prefixed+named dedicated originating branch as mentioned here, and close this PR.

**Comment by anushka255** [comment]
I will close this PR and split my local branch into three - one per issue. I believe this can be done by creating a new branch starting from each commit. Once it's done, I will reset the current branch. 

Sorry about that. I was under the impression that this was okay as long as we are working on issues related to `remote`. I will be more mindful of this in the future.

**Comment by vineetbansal** [comment]
Thanks - I wouldn't worry about resetting any branch (once a branch is merged to `main`, it's job is done - i.e. I don't care about the `vb/remote` branch anymore). This should allow you more flexibility (moving files manually around your local machine and creating new branches).

**Pull request closed without merging**
